# Generated by Django 2.1.7 on 2019-03-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190321_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, height_field=10, upload_to='products/static/product/media/', width_field=10),
            preserve_default=False,
        ),
    ]
