# Generated by Django 2.1.7 on 2019-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=10, upload_to='products/statica/product/media/', width_field=10),
        ),
    ]
